### ISSUE TITLE
How to use LineMessagingAPISDK?

### ISSUE THREAD

**Issue by Kornrathak** [kenakamu/line-bot-sdk-csharp#1]
I want to use Framework but i don't understand to call it.

**Comment by kenakamu** [comment]
I recommend start from Visual Studio template which include the library.
Did you setup Line Developer account and Bot API?

**Comment by Kornrathak** [comment]
Yes, i did. I start template but I test default new project is 

> {"Message":"An error has occurred.","ExceptionMessage":"The given header was not found.","ExceptionType":"System.InvalidOperationException","StackTrace":" at System.Net.Http.Headers.HttpHeaders.GetValues(String name)\r\n at Line_With_BotFramework_Application1.Controllers.LineMessagesController.d__1.MoveNext() in C:\\Users\\Ex1stCeed\\Documents\\project\\LINE-BOT-PHP-Starter\\Line With BotFramework Application1\\Line With BotFramework Application1\\Controllers\\LineMessagesController.cs:line 95\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at Line_With_BotFramework_Application1.Controllers.LineMessagesController.d__0.MoveNext() in C:\\Users\\Ex1stCeed\\Documents\\project\\LINE-BOT-PHP-Starter\\Line With BotFramework Application1\\Line With BotFramework Application1\\Controllers\\LineMessagesController.cs:line 31\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()"

![image](https://cloud.githubusercontent.com/assets/14836406/21843591/292b4528-d81e-11e6-88de-2bad8ca454f2.png)

s.p. I'am beginner

**Comment by kenakamu** [comment]
Are you already using Bot Framework? If not, and if you don't have any plan to use it, then you shall use another template, Line Bot Application.

**Comment by Kornrathak** [comment]
I'm already for use but my global is use c# with line messaging api because i don't used develop web api. i try to read bot framework.

**Comment by Kornrathak** [comment]
Ok, Thank you for recommend. I understand code structure but i find problem. i don't understand DirectLineSecret value. What's mean?

**Comment by kenakamu** [comment]
If you are using Microsoft Bot Framework and registered your bot at dev.botframework.com, then you can add Direct Line Channel. In the channel, you can get Direct Line Secret. The idea is the message coming from LINE will be redirected to Direct Line and reply will be redirected to LINE platform.

**Comment by kenakamu** [comment]
Hope everything went well. Closing for now.
