### ISSUE TITLE
how cai i push message without request

### ISSUE THREAD

**Issue by fit-sys** [kenakamu/line-bot-sdk-csharp#10]
thank you and great job with this api and template.
i implimented reply message. it works well.
but ,i can not understand about push message via api. could you make some example about push message. thank you.

**Comment by kenakamu** [comment]
Thanks for using it. I totally missed this sorry. I will add the sample this weekend but you can simply use push method.

**Comment by kenakamu** [comment]
Just let me know what is your scenario? Do you push the message from other system or just use timer thing inside bot?

**Comment by fit-sys** [comment]
thank you for your reply. yes. i want to do push message from other system any time i want to.

**Comment by kenakamu** [comment]
You can add controller like this in your solution and call it.

```csharp
using LineMessagingAPISDK;
using LineMessagingAPISDK.Models;
using System.Collections.Generic;
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Http;

namespace LineBotApplication1.Controllers
{
    public class SendMessageController : ApiController
    {
        private LineClient lineClient = new LineClient(ConfigurationManager.AppSettings["ChannelToken"].ToString());
        public async Task Post(string to, string message)
        {
            PushMessage push = new PushMessage();
            push.To = to;
            push.Messages = new List<Message>();
            push.Messages.Add(new TextMessage(message));
            await lineClient.PushAsync(push);
        }
    }
}
```
