### ISSUE TITLE
How can we parse emoticon with text message?

### ISSUE THREAD

**Issue by MihirGosai** [kenakamu/line-bot-sdk-csharp#12]
Recently I sent an emoticon with text message. As mentioned [here ](https://devdocs.line.me/en/#text), emoticon does not show up correctly in the browser. So, I expected an unicode value of an emoticon, but I got a keyword that is associated with emoticon. 

Example of text with emoticon that I receive as `message.text` is
`text: "Hello (charming)"`

If there is any way to parse that keyword into emoticon, please share an example.

**Comment by kenakamu** [comment]
What do you want to do actually? For my understanding, you send emoji from LINE to bot, and you want to handle what emoji has been sent to the Bot?

**Comment by MihirGosai** [comment]
Yes, you got it right. I want to see what emoticon has been sent and how it looks as an image.

**Comment by kenakamu** [comment]
I will try my side as well but if the data comes as (xxx) form, then that could be the only information we can get.

**Comment by kenakamu** [comment]
i don't know what is (charming) icon but hospital just worked. Which icon is charming?

**Comment by MihirGosai** [comment]
https://i.imgur.com/QghHNAo.png
Please see this emoticon in line messenger app.

**Comment by kenakamu** [comment]
It's interesting that Japanese emoji works, but not English ones. On the other hand, it returns emoticon like below.

```csharp
  var a = char.ConvertFromUtf32(int.Parse("10004C", System.Globalization.NumberStyles.HexNumber));
                replyMessage = new TextMessage(a);
```

**Comment by MihirGosai** [comment]
One more example:
😎hello is coming as (Moon cool)hello
Screenshot: https://i.imgur.com/pPkCNyq.jpg

**Comment by kenakamu** [comment]
I will look into it but as it seems like message comes as (moon cool) when receiving in API, there may be nothing I can do.

**Comment by MihirGosai** [comment]
Ok, thanks for quick reply.
