### ISSUE TITLE
DurationInMilliseconds of AudioMessage class should be long instead of int.

### ISSUE THREAD

**Issue by MihirGosai** [kenakamu/line-bot-sdk-csharp#14]
I have a audio file that is 1 minute long i.e. 60000 Milliseconds.
Can you please use `long` instead of `int` for the same?
P.S. file size is 800kb only.

**Comment by kenakamu** [comment]
Can you simply set 60000 as int?

**Comment by MihirGosai** [comment]
Sorry, it was a mistake. Error occurred because it was trying to fill 60000.50 as a value.

**Comment by kenakamu** [comment]
oh okay. :)
