### ISSUE TITLE
send image to BOT cause 500 Internal Server Error

### ISSUE THREAD

**Issue by LoonNg** [kenakamu/line-bot-sdk-csharp#2]
hello, I get 500 Internal Server Error when sending image to BOT
after deubg, i find the error is from Media medis = await lineClient.GetContent(message.Id);
i use ngrok to do webhook 
any idea, thanks!

**Comment by kenakamu** [comment]
I couldn't repro the issue. Could you troubleshoot by directly calling GET https://api.line.me/v2/bot/message/{messageId}/content?.

**Comment by kenakamu** [comment]
Hi,  by some reason, the uploaded nuget package version had the issue. I am sorry. I just re-upload the package and it shouldn't have the issue. I tested with my local package. my bad..

**Comment by LoonNg** [comment]
Thanks! This library is very good!

**Comment by kenakamu** [comment]
actually I am updating the library to support more features now. Pleas wait a couple of days.
