### ISSUE TITLE
about webhook URL

### ISSUE THREAD

**Issue by gamemun01** [kenakamu/line-bot-sdk-csharp#3]
I create project with LineBotApplication template and already update Web.config to use my Secret and Token and then update webhook URL but I get verify "A http status of the response was '500 Internal Server Error'. like this how to solve this problem?
![sss](https://cloud.githubusercontent.com/assets/8478142/24941939/1cb65e30-1f78-11e7-9e27-6e088dcd5092.png)
"

**Comment by kenakamu** [comment]
As it says 500, it should go through to your bot application. Can you debug by putting breakpoint in post method in messagecontroller?

**Comment by gamemun01** [comment]
I cannot debug becuase I Deploy to IIS server for public

**Comment by kenakamu** [comment]
Okay, I will try it tonight. If you deploy to azure then you can live debug :)

**Comment by kenakamu** [comment]
It looks like what they send when verifying has been changed, but it should work anyway. Just ignore the error for now and let me know if it works from your Line.

**Comment by kenakamu** [comment]
by the way, i found a bit of issue due to SDK update (1.2). I will fix and re-package it later. Sorry for inconvenience, but you can still go ahead coding by using SDK 1.1.

**Comment by gamemun01** [comment]
Ok thank you

**Comment by gamemun01** [comment]
Now I using SDK 1.1 but It have same issue  I not sure what I wrong config it or not. 
Can you check my code from this repo
https://github.com/gamemun01/cbot1234

**Comment by kenakamu** [comment]
1.1 still has the issue and just ignore it :) configure line and talk to bot from line

**Comment by gamemun01** [comment]
Thank you, Now I can talk to bot and developing :D

**Comment by kenakamu** [comment]
Great!! Plz consider using bot framework too
