### ISSUE TITLE
AudioMessage and VideoMessage not working?

### ISSUE THREAD

**Issue by MikeAbyss** [kenakamu/line-bot-sdk-csharp#4]
Does the audio / video message work for this SDK?

I'm currently using 

return new VideoMessage("https://dwknz3zfy9iu1.cloudfront.net/uscenes_h-264_hd_test.mp4", @"https://img.rasset.ie/000df3e1-800.jpg");

to test functionality. In the Line Messenger I see the preview, but when I click to load the video it does not work. Same thing happens for Audio Messages. "Cannot load this video as it is no longer available"

Many thanks!

**Comment by kenakamu** [comment]
LINE itself has own limitation for audio format and length. Please see messaging API doc for detail

**Comment by MikeAbyss** [comment]
Yes, I followed the limitations however I am still not able to send audio message.
Link is HTTPS
File format M4A
Duration: 4 s
Size: 31.4kbs

The file is sitting on a local ASP.NET MVC application I'm using Ngrok for local development

E.G https://test.ngrok.io/Content/audio.m4a 

I can view it in my browser but when it gets sent to Line it will give me "Cannot load this video as it is no longer available".  "" Any clue?

This is how I'm using it.

var xLink = @"https://test.ngrok.io/Content/audio.m4a";
return new AudioMessage(xLink , 4852);

**Comment by kenakamu** [comment]
I also cannot access the file from my end. The audio file needs to be in accessible from anywhere

**Comment by MikeAbyss** [comment]
Sorry here it is, but again Line doesn't recognize it https://de0bc487.ngrok.io/Content/sample.m4a

**Comment by kenakamu** [comment]
When I tested, it does play sounds, but it length shows as 0:00. I will dig in further.

**Comment by kenakamu** [comment]
I use Postman to directly push the message to line, which end up same result. time length 0:00 but it plays the sound as expected. It seems the issue is on line platform, not SDK.
