### ISSUE TITLE
Imagemap

### ISSUE THREAD

**Issue by gilangbh** [kenakamu/line-bot-sdk-csharp#5]
This does not seem to already support Imagemap which are images with one or more links. You can assign one link for the entire image or multiple links which correspond to different regions of the image.

Please refer to: https://devdocs.line.me/en/#imagemap-message

Is it in development or roadmap for this library? Thank you.

**Comment by kenakamu** [comment]
Hi does this satisfy your needs?

https://github.com/kenakamu/line-bot-sdk-csharp/blob/master/LineMessagingAPISDK/LineMessagingAPISDK/Models/ImageMapMessage.cs

**Comment by gilangbh** [comment]
Oops sorry. Last time I updated my Nuget package was over a month ago, did not notice it has been added already. Thank you.

**Comment by kenakamu** [comment]
Sure thing! Please let me know if there are issues

**Comment by kenakamu** [comment]
Actually I found a bug on ImageMap. I updated the SDK and template now has image map sample
