### ISSUE TITLE
watermark should not assign greater then 1 in LineMessagesController.cs?

### ISSUE THREAD

**Issue by rainmakerho** [kenakamu/line-bot-sdk-csharp#7]
if i set "watermark = "2"; ", the my bot dialog will receive twice message!
should i always set watermark = null ?
thank for your help.

**Comment by kenakamu** [comment]
Watermark should be handled automatically. The purpose of it is to get the messages which are not getting yet. 

So if you keep passing null, it returns all the messages in the conversation from first. If you pass 2, then it returns messages after 2nd. 

So every time you fetch messages from direct line, you should update watermark with latest value. The latest value will be returned as part of getactitivies.

**Comment by rainmakerho** [comment]
@kenakamu  Thanks for your help.
I have another question about use line bot with bot framework.
i add [MicrosoftDX/AuthBot](https://github.com/MicrosoftDX/AuthBot)  to LineBotApplication  project.
the source are at [rainmakerho/BotAuth](https://github.com/rainmakerho/BotAuth).
line couldn't get resume message when i call Conversation.ResumeAsync(state.ConversationReference, message);
Is there a way to let LINE Direct Line to get the message?
Thanks you.

**Comment by kenakamu** [comment]
Sure thing. I guess you are using node.js? In any case I need to investigate the authbot usage. Give me some time

**Comment by rainmakerho** [comment]
Hi, @kenakamu  
I am using C#.  
Thanks for your help.

**Comment by kenakamu** [comment]
I close this and create new issue to clarify the issue.
