### ISSUE TITLE
Issue with AuthBot

### ISSUE THREAD

**Issue by kenakamu** [kenakamu/line-bot-sdk-csharp#8]
I have another question about use line bot with bot framework.
 i add MicrosoftDX/AuthBot to LineBotApplication project.
 the source are at rainmakerho/BotAuth.
 line couldn't get resume message when i call Conversation.ResumeAsync(state.ConversationReference, message);
 Is there a way to let LINE Direct Line to get the message?
 Thanks you.

**Comment by kenakamu** [comment]
@rainmakerho I added new issue here.

**Comment by kenakamu** [comment]
The cause was due to incomplete Channel Account. In the line connector, I only passed Id like below.
```csharp
From = new dl.ChannelAccount(lineEvent.Source.UserId)
```
But I had to pass name as well.

```csharp
From = new dl.ChannelAccount(lineEvent.Source.UserId, lineEvent.Source.UserId)
```
It is up to you which string you want to pass as name, but I simply duplicate id here. Please fix it or download the latest template.

**Comment by kenakamu** [comment]
Leave a comment

**Comment by rainmakerho** [comment]
Thank for your help. 
User => Line => LineMessagesController => MessagesController -> SigninCard => LineMessagesController -> Buttons Template (login url with ConversationReference) 

User => Line Click login url => Login.aspx -> click OK =>  MessagesController -> context.PostAsync("Please input validation number") 


LineMessagesController can't get "Please input validation number" message.

After User input validation number, LineMessagesController  can get "Please input validation number" messag" and others messages.

**Comment by kenakamu** [comment]
That is a limitation as direct line cannot get proactive message. If you want you can put the trick somewhere

**Comment by rainmakerho** [comment]
Hi @kenakamu , Thanks for your help.
