### ISSUE TITLE
Please add Multicast example in LineMessagesController.cs

### ISSUE THREAD

**Issue by MihirGosai** [kenakamu/line-bot-sdk-csharp#9]
I would appreciate if you add an example for **Multicast** in [LineMessagesController.cs](https://raw.githubusercontent.com/kenakamu/line-bot-sdk-csharp/master/LineBotApplication/LineBotApplication/Controllers/LineMessagesController.cs)

Thanks.

**Comment by kenakamu** [comment]
Sorry j missed this post. You can simply specify multiple MIDs in array but the question is where you get the mid. I will put sample later

**Comment by kenakamu** [comment]
Try this

```csharp
await lineClient.MulticastAsync(new List<string>() { to1, to2 }, new List<Message>() { new TextMessage(message) });
```
You need to get to addresses.

**Comment by MihirGosai** [comment]
Works Fine...
